"""add ledger_entries table

Revision ID: e7a3f8d2c1b4
Revises: c9da808b5967
Create Date: 2026-08-08 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a3f8d2c1b4'
down_revision: Union[str, Sequence[str], None] = 'c9da808b5967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ledger_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('entry_id', sa.Integer(), nullable=False),
        sa.Column('line_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('debit', sa.Numeric(14, 2), nullable=False),
        sa.Column('credit', sa.Numeric(14, 2), nullable=False),
        sa.Column('running_balance', sa.Numeric(14, 2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id']),
        sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id']),
        sa.ForeignKeyConstraint(['line_id'], ['journal_entry_lines.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('line_id', name='uq_ledger_line'),
    )
    op.create_index('idx_ledger_account_date', 'ledger_entries', ['account_id', 'date'])
    op.create_index('idx_ledger_entry', 'ledger_entries', ['entry_id'])
    op.create_index('ix_ledger_entries_date', 'ledger_entries', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_entries_date', table_name='ledger_entries')
    op.drop_index('idx_ledger_entry', table_name='ledger_entries')
    op.drop_index('idx_ledger_account_date', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
